config/routes.rb
# -*- encoding : utf-8 -*-
Taurus::Application.routes.draw do

##### Общие части #####

  concern :departments do
    get :charge_cards_form, on: :member
  end

  concern :teaching_places do
    get :training_assignments, on: :member
  end

  concern :training_assignments do
    resources :training_assignments do
      as_routes
      get :report, on: :collection
      get :join_selected, on: :collection
      get :split_by_disciplines, on: :member
      get :split_by_groups, on: :member
      get :new_charge_cards, on: :collection
      post :create_charge_cards, on: :collection
    end
  end

  concern :speciality_teaching_plans do
    get :teaching_plan_import, on: :collection
    post :teaching_plan_import, on: :collection
    get :teaching_plan, on: :member
  end

##### Отображение расписания #####

  root :to => redirect('/timetable/groups')

  namespace :timetable do
    resources :groups do
      get :qrcode, on: :member
    end
    resources :lecturers
    resources :classrooms
    root :to => redirect('/timetable/groups')
  end

##### Общее #####

post 'semesters/change' => 'application#change_current_semester'
resources :semesters, :only => [:index]
match 'help(/:page(.:format))', :controller => 'help', :action => 'show', :page => /(\w*\/?\w*)*/, :defaults => { :page => 'index' }, :as => :help

##### Редакторский раздел #####

  namespace :editor do
    root :to => redirect('/editor/groups')

    # Редактор по аудиториям
    namespace :classrooms do
      resources :classrooms
      resources :pairs
      resources :charge_cards
      resources :classrooms_sheets
      root :to => 'classrooms#index'
    end

    # Редактор по группам
    namespace :groups do
      resources :groups
      resources :pairs
      resources :classrooms
      resources :charge_cards
      root :to => 'groups#index'
    end

    # Справочные материалы
    namespace :reference do
      resources :groups
      resource :groups_list do
        resources :groups
      end
      resources :departments do as_routes end
      resources :disciplines do as_routes end
      resources :teaching_places do as_routes end
      resources :charge_cards do as_routes end
      get 'teaching_plans' => 'teaching_plans#index'
      get 'teaching_plans/:group_id' => 'teaching_plans#show'
      root :to => redirect('/editor/reference/classroom_sheets')
    end
  end

##### Раздел заведующего кафедрой #####

  get  'dept_head(/*parts)' => 'department/base#change_current_department'
  get  'department' => 'department/base#change_current_department'
  post 'department/change' => 'department/base#change_current_department'
  namespace :department, :path => '/department/:department_id', :department_id => /\d+/ do
    resources :teaching_places do
      as_routes
      record_select_routes
      get :training_assignments, on: :member
    end
    resources :disciplines do
      as_routes
      record_select_routes
    end
    resources :groups do
      as_routes
      collection do get :browse end
      member do
        post :select
        get  :teaching_plan
      end
    end
    resources :lecturers do
      as_routes
      record_select_routes
    end
    resources :charge_cards do
      as_routes
    end
    resources :specialities, concerns: [:speciality_teaching_plans] do
      as_routes
      member do
        get :add_charge_cards
        post :create_charge_cards
      end
    end
    resources :classrooms do as_routes end
    resource :charge_card_form, only: [:show, :edit, :save]
    concerns :training_assignments
    root :to => redirect {|env, req| "/department/#{req.params[:department_id]}/teaching_places" }
  end

##### Раздел деканата #####

  get  'faculty' => 'faculty/base#change_current_faculty'
  post 'faculty/change' => 'faculty/base#change_current_faculty'

  namespace :faculty, :path => '/faculty/:faculty_id', :faculty_id => /\d+/ do
    resources :specialities do
      as_routes
      concerns :speciality_teaching_plans
      member do
        post :generate_training_assignments
      end
      collection do
        post :generate_training_assignments
      end
    end
    resources :lecturers do as_routes end
    resources :groups do
      as_routes
      record_select_routes
    end
    resources :teaching_places do
      as_routes
      record_select_routes
    end
    resources :disciplines do
      as_routes
      record_select_routes
    end
    resources :departments, concerns: [:departments] do as_routes end
    concerns :training_assignments
    root :to => redirect('/supervisor/lecturers')
  end

##### Раздел супервайзера #####

  namespace :supervisor do
    resources :faculties do as_routes end
    resources :specialities, concerns: [:speciality_teaching_plans] do
      post :generate_training_assignments, on: :collection
      post :generate_training_assignments, on: :member
      as_routes
    end
    resources :groups do
      as_routes
      collection do get :browse end
      member do get :teaching_plan end
    end
    resources :classrooms do as_routes end
    resources :lecturers do as_routes end
    resources :teaching_places do
      as_routes
      record_select_routes
    end
    resources :charge_cards do as_routes end
    resources :disciplines do
      as_routes
      record_select_routes
    end
    resources :departments, concerns: [:departments] do as_routes end
    resources :semesters do as_routes end
    concerns :training_assignments
    root :to => redirect('/supervisor/lecturers')
  end

##### Администраторский раздел #####

  namespace :admin do
    resources :users do as_routes end
    resources :dept_heads do as_routes end
    resources :editors do as_routes end
    resources :supervisors do as_routes end
    resources :admins do as_routes end
    resources :departments do
      as_routes
      record_select_routes
    end
    resources :faculty_heads do as_routes end
    resources :faculties do
      as_routes
      record_select_routes
    end
    root :to => redirect('/admin/dept_heads')
  end

##### Аутентификация #####

  devise_for :user, :skip => [:sessions]
  devise_scope :user do
    get    'user/login' => 'devise/sessions#new',      :as => :new_user_session
    post   'user/login' => 'devise/sessions#create',    :as => :user_session
    delete 'user/logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  match "/:rolename/login" => redirect("/user/login")

  match '/:controller(/:action(/:id))'

end

app/controllers/department/classrooms_controller.rb
class Department::ClassroomsController < Department::BaseController
  active_scaffold :classroom do |conf|
    conf.actions.exclude :create
    conf.columns = [:building, :name, :title, :department, :department_lock, :capacity, :properties]
    conf.update.columns = [:title, :capacity, :properties]
    conf.columns[:building].clear_link
    conf.columns[:department].clear_link
  end

  def before_update_save(record)
    record[:properties] = params[:record][:properties]
  end

  # Records are filtered according to CanCan abilities.

end 

app/controllers/editor/classrooms/charge_cards_controller.rb
# -*- encoding : utf-8 -*-
class Editor::Classrooms::ChargeCardsController < Editor::BaseController
  def index
    charge_card_search = params[:charge_card].to_s.split
    classroom = Classroom.find(params[:classroom_id])
    if classroom.department_lock and classroom.department
      charge_card = ChargeCard.with_recommended_first_for(classroom.department).where(:semester_id => current_semester.id).each do |c|
        c.set_recommended_dept(classroom.department)
      end
    else
      charge_card = ChargeCard.where(:semester_id => current_semester.id)
    end
    charge_card_search.each do |s|
      charge_card = charge_card.select { |c| c.editor_name_include? s }
    end
    respond_to do |format|
      format.json { render :json => charge_card.to_json(:only => [:id], :methods => [:editor_name_with_recommendation])}
    end
  end
end

app/controllers/editor/classrooms/classrooms_controller.rb
# -*- encoding : utf-8 -*-
class Editor::Classrooms::ClassroomsController < Editor::BaseController

  def index
    flash[:error] = nil
    session[:classroom_editor] = {:classrooms => []} unless session[:classroom_editor]
    except = session[:classroom_editor][:classrooms].any? ? session[:classroom_editor][:classrooms] : "0"
    classroom = params[:classroom].to_s.gsub('%', '\%').gsub('_', '\_') + '%'
    @classrooms = Classroom.where(['classrooms.id NOT IN (?) AND classrooms.name ILIKE ?', except, classroom]).includes(:building)
    respond_to do |format|
      format.html
      format.json { render :json => @classrooms.to_json(:only => [:id, :name], :include => { :building => { :only => :name } } )}
    end
  end

  def show
    @days = Timetable.days
    @times = Timetable.times
    @weeks = Timetable.weeks
    @classroom = Classroom.includes(:pairs).find(params[:id])
    unless @classroom
      flash[:error] = 'Нет аудитории с таким названием'
    else
      @pairs = @classroom.pairs.in_semester(current_semester).order("active_at ASC")
      session[:classroom_editor] = {:classrooms => []} unless session[:classroom_editor]
      session[:classroom_editor][:classrooms] << @classroom.id unless session[:classroom_editor][:classrooms].include? @classroom.id
      respond_to do |format|
        format.js
      end
    end
  end

  def edit

  end

  def update

  end

  def destroy
    if session[:classroom_editor].include? :classrooms
      @id = params[:id].to_i
      session[:classroom_editor][:classrooms].delete(@id)
      respond_to do |format|
        format.js
      end
    end
  end
end

app/controllers/editor/classrooms/classrooms_sheets_controller.rb
# -*- encoding : utf-8 -*-
class Editor::Classrooms::ClassroomsSheetsController < Editor::BaseController
  def index
    @buildings = Building.all
  end
  
  def show
    @weeks = Timetable.weeks
    @days = Timetable.days
    @times = Timetable.times
    @building = Building.find_by_id(params[:id].to_i, :include => [{:classrooms => :pairs}])
    #@classrooms_sheet.classrooms = Classroom.all(:include => :pairs, :conditions => {:building_id => @classrooms_sheet.building.id}).sort_by { |c| c.name.to_i}
  end
end

app/controllers/editor/classrooms/pairs_controller.rb
# -*- encoding : utf-8 -*-
class Editor::Classrooms::PairsController < Editor::BaseController
  layout nil
  layout 'application', :except => :edit

  def create
    flash[:error] = nil
    @pair = Pair.new do |p|
      p.classroom_id = params[:classroom_id]
      p.day_of_the_week = params[:day_of_the_week]
      p.pair_number = params[:pair_number]
      p.week = params[:week]
      p.active_at = current_semester.start
      p.expired_at = current_semester.end
    end
    @container = params[:container]
    unless @pair.valid?
      flash[:error] = @pair.errors[:base].to_a.join('<br />').html_safe
      @pair = nil
    else
      @pair.save
    end

    respond_to do |format|
      format.js
    end
  end

  def edit
    @pair = Pair.find_by_id(params[:id])

    respond_to do |format|
      format.js
    end
  end

  def update
    flash[:error] = nil
    @pair = Pair.find_by_id(params[:id].to_i, :include => [:subgroups])
    @prev_pair = @pair.clone
    @prev_pair.readonly!
    if params[:get_subgroups] && params[:pair]
      @pair.attributes = params[:pair]
      unless @pair.valid?
        flash[:error] = @pair.errors[:base].to_a.join('<br />').html_safe
        @pair.reload
      else
        @pair.save
        @pair.subgroups.destroy_all
        @pair.charge_card.jets.each do |jet|
          subgroup = @pair.subgroups.new(:jet_id => jet.id, :number => 0)
          unless subgroup.valid?
            flash[:error] = subgroup.errors[:base].to_a.join('<br />').html_safe
          else
            subgroup.save
          end
        end
        redirect_to :action => 'edit'
      end
    elsif params[:classroom]
      @pair.classroom_id = params[:classroom].to_i
      @pair.day_of_the_week = params[:day_of_the_week].to_i if params[:day_of_the_week]
      @pair.week = params[:week].to_i if params[:week]
      @pair.pair_number = params[:pair_number].to_i if params[:pair_number]
      unless @pair.valid?
        flash[:error] = @pair.errors[:base].to_a.join('<br />').html_safe
        @pair.reload
      else
        @pair.save
      end

      respond_to do |format|
        format.js
      end
    else
      @pair.attributes = params[:pair]
      unless @pair.valid?
        flash[:error] = @pair.errors[:base].to_a.join('<br />').html_safe
        @pair.reload
        @pair.charge_card_id = nil
        @pair.subgroups.destroy_all
        @pair.save
        redirect_to :action => 'edit'
      else
        @pair.save
        
        respond_to do |format|
          format.js
        end
      end
    end
  end

  def destroy
    flash[:error] = nil
    @id = params[:id].to_i
    pair = Pair.find_by_id(@id)
    @pair = pair.clone
    @pair.readonly!
    pair.destroy

    respond_to do |format|
      format.js
    end
  end
end

app/controllers/supervisor/classrooms_controller.rb
# -*- encoding : utf-8 -*-
class Supervisor::ClassroomsController < Supervisor::BaseController
  active_scaffold do |config|
    config.actions << :delete
    config.columns = [:building, :name, :title, :department, :department_lock, :capacity, :properties]
    config.columns[:building].form_ui = :select
    config.columns[:department].form_ui = :select
    config.columns[:department_lock].form_ui = :checkbox
    config.columns[:building].clear_link
    config.columns[:department].clear_link
  end

  def before_update_save(record)
    record[:properties] = params[:record][:properties]
  end

end

app/controllers/timetable/classrooms_controller.rb
class Timetable::ClassroomsController < Timetable::BaseController

  def index
    @buildings = Building.includes(:classrooms).reorder("buildings.id,(substring(classrooms.name, '^[0-9]+'))::int,substring(classrooms.name, '[^0-9_].*$')")
    @buildings = @buildings.where("classrooms.name ILIKE ? OR classrooms.title ILIKE ? OR buildings.name ILIKE ?", *(["%#{params[:classroom]}%"]*3)) if params[:classroom]
    if params[:day_of_the_week] and params[:week] and params[:pair_number]
      week_filter = params[:week] == '0' ? [0,1,2] : [params[:week], 0]
      unwanted_classroom_ids = Pair.where(week: week_filter, day_of_the_week: params[:day_of_the_week], pair_number: params[:pair_number]).pluck(:classroom_id).uniq.compact
      if unwanted_classroom_ids.any?
        @buildings = @buildings.where("classrooms.id NOT IN (#{unwanted_classroom_ids.join(",")})")
      end
    end
    respond_to do |format|
      format.html do
        if @buildings.count == 1 and @buildings.first.classrooms.count == 1
          redirect_to timetable_classroom_path(@buildings.first.classrooms.first)
        end
      end
      format.json do
        render :json => @buildings.to_json(only: [:id, :name], include: {classrooms: {only: [:id, :title, :name]}})
      end
    end
  end

  def show
    @id = params[:id].to_i
    unless @classroom = Classroom.find_by_id(@id)
      suffix = @terminal ? '?terminal=true' : ''
      redirect_to :controller => 'timetable/classrooms' + suffix
    else
      pairs = @classroom.pairs.includes(:subgroups).in_semester(current_semester).flatten
      @days = Timetable.days
      @times = Timetable.times
      @weeks = Timetable.weeks
      @pairs = Array.new(@days.size).map!{Array.new(@times.size).map!{Array.new(@weeks.size + 1).map!{Array.new}}}
      pairs.each do |pair|
        @pairs[pair.day_of_the_week - 1][pair.pair_number - 1][pair.week] << pair
      end
    end
  end

end

app/helpers/department/classrooms_helper.rb
module Department::ClassroomsHelper

  def properties_column(record, column)
    record.properties_human
  end

end

app/helpers/editor/classrooms/charge_cards_helper.rb
# -*- encoding : utf-8 -*-
module Editor::Classrooms::ChargeCardsHelper
end

app/helpers/editor/classrooms/classrooms_helper.rb
# -*- encoding : utf-8 -*-
module Editor::Classrooms::ClassroomsHelper
end

app/helpers/editor/classrooms/classrooms_sheets_helper.rb
# -*- encoding : utf-8 -*-
module Editor::Classrooms::ClassroomsSheetsHelper
  def buildings_for_select
    Building.all.map { |d| [d.name, d.id]}
  end
end

app/helpers/editor/classrooms/groups_helper.rb
# -*- encoding : utf-8 -*-
module Editor::Classrooms::GroupsHelper
end

app/helpers/supervisor/classrooms_helper.rb
# -*- encoding : utf-8 -*-
module Supervisor::ClassroomsHelper

  def properties_column(record, column)
    record.properties_human
  end

end

app/helpers/timetable/classrooms_helper.rb
module Timetable::ClassroomsHelper
end

app/views/editor/classrooms/classrooms/_container.html.haml
- if colspan == 2
  - cont = "_grid#{pair.classroom_id}_week0_day#{pair.day_of_the_week}_time#{pair.pair_number}"
  %td{ :id => "td#{cont}", :colspan => "2" }  
    .receiver{ :id => "container#{cont}_index0", :grid_id => "#{pair.classroom_id}", :week_number => "0", :day_of_the_week => "#{pair.day_of_the_week}", :pair_number => "#{pair.pair_number}" }
    = render :partial => '/editor/classrooms/classrooms/recv_mgmt_panel', :locals => {:rcv_count => 1}
- elsif colspan == 1
  - cont1 = "_grid#{pair.classroom_id}_week1_day#{pair.day_of_the_week}_time#{pair.pair_number}"
  - cont2 = "_grid#{pair.classroom_id}_week2_day#{pair.day_of_the_week}_time#{pair.pair_number}"
  %td{ :id => "td#{cont1}", :colspan => "1" }  
    .receiver{ :id => "container#{cont1}_index0", :grid_id => "#{pair.classroom_id}", :week_number => "1", :day_of_the_week => "#{pair.day_of_the_week}", :pair_number => "#{pair.pair_number}" }
    = render :partial => '/editor/classrooms/classrooms/recv_mgmt_panel', :locals => {:rcv_count => 1}
  %td{ :id => "td#{cont2}", :colspan => "1" }  
    .receiver{ :id => "container#{cont2}_index0", :grid_id => "#{pair.classroom_id}", :week_number => "2", :day_of_the_week => "#{pair.day_of_the_week}", :pair_number => "#{pair.pair_number}" }
    = render :partial => '/editor/classrooms/classrooms/recv_mgmt_panel', :locals => {:rcv_count => 1}

app/views/editor/classrooms/classrooms/_day.html.haml
= render :partial => 'week', :collection => @weeks, :locals => {:grid => grid, :time => time, :day => day_counter + 1}

app/views/editor/classrooms/classrooms/_day_header.html.haml
%th{:colspan => 2}
  = day_header

app/views/editor/classrooms/classrooms/_grid.html.haml
- grid_id = "grid_#{h(grid.id)}"
.grid{:id => "#{grid_id}"}
  %table
    %tr
      %th{:colspan => 13}
        Аудитория #{grid.name} (#{grid.building.name}).
        Вместимость: #{grid.capacity ? grid.capacity.to_s + ' человек.' : 'не указана.'}
        - if grid.department
          Кафедра: #{grid.department.short_name}.
          - if grid.department_lock
            Рекомендуется ставить пары только для этой кафедры!
        .closebutton{:class => "grid_close", :grid_id => "#{grid.id}"}
    %tr
      %th
      = render :partial => 'day_header', :collection => @days
    %tr
      %th
      - 6.times do
        = render :partial => 'week_header', :collection => @weeks
    = render :partial => 'time', :collection => @times, :locals => {:grid => grid.id}

app/views/editor/classrooms/classrooms/_recv_mgmt_panel.html.haml
.grid_mgmt_panel
  %img.receiver_add{:src => image_path("plus.png"), :alt => "+"}
  %img.receiver_prev{:src => image_path("control-180.png"), :alt => "<"}
  %img.receiver_next{:src => image_path("control.png"), :alt => ">"}
  .receiver_count 1/#{rcv_count}

app/views/editor/classrooms/classrooms/_time.html.haml
%tr
  %th
    = time
  = render :partial => 'day', :collection => @days, :locals => {:grid => grid, :time => time_counter + 1}

app/views/editor/classrooms/classrooms/_week.html.haml
- td_id = "td_grid#{grid}_week#{week_counter + 1}_day#{day}_time#{time}"
- id = "container_grid#{grid}_week#{week_counter + 1}_day#{day}_time#{time}_index0"
%td{ :id => "#{td_id}", :colspan => "1"}  
  .receiver{ :id => "#{id}", :grid_id => "#{grid}", :week_number => "#{week_counter + 1}", :day_of_the_week => "#{day}", :pair_number => "#{time}", :index => 0 }
  = render :partial => 'recv_mgmt_panel', :locals => {:rcv_count => 1}

app/views/editor/classrooms/classrooms/_week_header.html.haml
%th
  = week_header

app/views/editor/classrooms/classrooms/destroy.js.erb
<% grid_id = escape_javascript "grid_#{@id}" %>
jQuery(document).ready(function($){
    $('#<%= grid_id %>').fadeOut('fast', function() {
        $('#<%= grid_id %>').remove();
        $('#classroom_name').focus();
        return false;
    });
});

app/views/editor/classrooms/classrooms/index.html.haml
- title "Редактор расписания по аудиториям"

.info
  %p<
    <strong>Внимание!</strong> Вы составляете расписание на #{current_semester}.

.workspace
  #form
    %p
      = 'Аудитория:'
      %br
      %input{:id => "classroom_name", :size => 10}
- if @classroom_id
  = javascript_tag("jQuery.get('"+editor_classrooms_classroom_path(@classroom_id)+"');")
- elsif session[:classroom_editor].include? :classrooms and session[:classroom_editor][:classrooms].any?
  - session[:classroom_editor][:classrooms].each do |classroom_id|
    - classroom = Classroom.find(classroom_id)
    = javascript_tag("jQuery.get('"+editor_classrooms_classroom_path(classroom)+"');")

app/views/editor/classrooms/classrooms/show.js.erb
jQuery(document).ready(function($){
    $('#form').before('<%= escape_javascript render :partial => 'grid', :object => @classroom %>');
    $('.receiver').droppable({
        accept: '.pair',
        over: function(){ $(this).addClass('hovered_receiver');},
        out: function(){ $(this).removeClass('hovered_receiver');},
        drop: function(event, ui){
            $.post('/editor/classrooms/pairs/' + ui.draggable.attr('id'), {
                _method: 'put',
                classroom: $(this).attr('grid_id'),
                week: $(this).attr('week_number'),
                day_of_the_week: $(this).attr('day_of_the_week'),
                pair_number: $(this).attr('pair_number'),
                container: $(this).attr('id'),
                index: $('.receiver', $(this).parent()).not('.hidden_receiver').prevAll('.receiver').length
            }, null, "script");
            $(this).removeClass('hovered_receiver');
        }
    });
    var paircells = new Array();
    <% @pairs.each do |pair| %>
    var index = '<%= escape_javascript "grid#{@classroom.id}_week#{pair.week}_day#{pair.day_of_the_week}_time#{pair.pair_number}" %>';
    if (paircells[index] == null)
        paircells[index] = 0;
    else
        paircells[index]++;
      <% if pair.week == 0 %>
        if (!paircells[index]) {
            $('#td_grid<%= pair.classroom_id %>_week1_day<%= pair.day_of_the_week %>_time<%= pair.pair_number %>').replaceWith('<%= escape_javascript render :partial => "/editor/classrooms/classrooms/container", :locals => {:pair => pair, :colspan => 2, :index => 0} %>');
            $('#td_grid<%= pair.classroom_id %>_week2_day<%= pair.day_of_the_week %>_time<%= pair.pair_number %>').remove();
        }
      <% end %>
      if (paircells[index]) {
        var newRcv = $('#<%= escape_javascript "container_grid#{@classroom.id}_week#{pair.week}_day#{pair.day_of_the_week}_time#{pair.pair_number}_index0" %>').clone().empty();
        newRcv.attr('id', '<%= escape_javascript "container_grid#{@classroom.id}_week#{pair.week}_day#{pair.day_of_the_week}_time#{pair.pair_number}_index" %>'+paircells[index]);
        newRcv.attr('index', paircells[index]);
        newRcv.addClass('hidden_receiver')
        var td_id = '#<%= escape_javascript "td_grid#{pair.classroom_id}_week#{pair.week}_day#{pair.day_of_the_week}_time#{pair.pair_number}" %>';
        $(td_id).append(newRcv);
        $(td_id+'>.grid_mgmt_panel').detach().appendTo(td_id); // Move management panel to the end of cell
        // Update the counters in management panel
        var grid_context = $(td_id+'>.grid_mgmt_panel').parent();
        var count = $('.receiver', grid_context).length;
        $('.receiver_count', grid_context).text("1/"+count);
      }
      $('#<%= escape_javascript "container_grid#{@classroom.id}_week#{pair.week}_day#{pair.day_of_the_week}_time#{pair.pair_number}_index" %>'+paircells[index]).append(
        '<%= escape_javascript render :partial => '/editor/classrooms/pairs/pair', :object => pair %>'
      );        
    <% end %>
    $('.pair').draggable();
    $('#classroom_name').val('');
});