config/routes.rb
# -*- encoding : utf-8 -*-
Taurus::Application.routes.draw do

##### Общие части #####

  concern :departments do
    get :charge_cards_form, on: :member
  end

  concern :teaching_places do
    get :training_assignments, on: :member
  end

  concern :training_assignments do
    resources :training_assignments do
      as_routes
      get :report, on: :collection
      get :join_selected, on: :collection
      get :split_by_disciplines, on: :member
      get :split_by_groups, on: :member
      get :new_charge_cards, on: :collection
      post :create_charge_cards, on: :collection
    end
  end

  concern :speciality_teaching_plans do
    get :teaching_plan_import, on: :collection
    post :teaching_plan_import, on: :collection
    get :teaching_plan, on: :member
  end

##### Отображение расписания #####

  root :to => redirect('/timetable/groups')

  namespace :timetable do
    resources :groups do
      get :qrcode, on: :member
    end
    resources :lecturers
    resources :classrooms
    root :to => redirect('/timetable/groups')
  end

##### Общее #####

post 'semesters/change' => 'application#change_current_semester'
resources :semesters, :only => [:index]
match 'help(/:page(.:format))', :controller => 'help', :action => 'show', :page => /(\w*\/?\w*)*/, :defaults => { :page => 'index' }, :as => :help

##### Редакторский раздел #####

  namespace :editor do
    root :to => redirect('/editor/groups')

    # Редактор по аудиториям
    namespace :classrooms do
      resources :classrooms
      resources :pairs
      resources :charge_cards
      resources :classrooms_sheets
      root :to => 'classrooms#index'
    end

    # Редактор по группам
    namespace :groups do
      resources :groups
      resources :pairs
      resources :classrooms
      resources :charge_cards
      root :to => 'groups#index'
    end

    # Справочные материалы
    namespace :reference do
      resources :groups
      resource :groups_list do
        resources :groups
      end
      resources :departments do as_routes end
      resources :disciplines do as_routes end
      resources :teaching_places do as_routes end
      resources :charge_cards do as_routes end
      get 'teaching_plans' => 'teaching_plans#index'
      get 'teaching_plans/:group_id' => 'teaching_plans#show'
      root :to => redirect('/editor/reference/classroom_sheets')
    end
  end

##### Раздел заведующего кафедрой #####

  get  'dept_head(/*parts)' => 'department/base#change_current_department'
  get  'department' => 'department/base#change_current_department'
  post 'department/change' => 'department/base#change_current_department'
  namespace :department, :path => '/department/:department_id', :department_id => /\d+/ do
    resources :teaching_places do
      as_routes
      record_select_routes
      get :training_assignments, on: :member
    end
    resources :disciplines do
      as_routes
      record_select_routes
    end
    resources :groups do
      as_routes
      collection do get :browse end
      member do
        post :select
        get  :teaching_plan
      end
    end
    resources :lecturers do
      as_routes
      record_select_routes
    end
    resources :charge_cards do
      as_routes
    end
    resources :specialities, concerns: [:speciality_teaching_plans] do
      as_routes
      member do
        get :add_charge_cards
        post :create_charge_cards
      end
    end
    resources :classrooms do as_routes end
    resource :charge_card_form, only: [:show, :edit, :save]
    concerns :training_assignments
    root :to => redirect {|env, req| "/department/#{req.params[:department_id]}/teaching_places" }
  end

##### Раздел деканата #####

  get  'faculty' => 'faculty/base#change_current_faculty'
  post 'faculty/change' => 'faculty/base#change_current_faculty'

  namespace :faculty, :path => '/faculty/:faculty_id', :faculty_id => /\d+/ do
    resources :specialities do
      as_routes
      concerns :speciality_teaching_plans
      member do
        post :generate_training_assignments
      end
      collection do
        post :generate_training_assignments
      end
    end
    resources :lecturers do as_routes end
    resources :groups do
      as_routes
      record_select_routes
    end
    resources :teaching_places do
      as_routes
      record_select_routes
    end
    resources :disciplines do
      as_routes
      record_select_routes
    end
    resources :departments, concerns: [:departments] do as_routes end
    concerns :training_assignments
    root :to => redirect('/supervisor/lecturers')
  end

##### Раздел супервайзера #####

  namespace :supervisor do
    resources :faculties do as_routes end
    resources :specialities, concerns: [:speciality_teaching_plans] do
      post :generate_training_assignments, on: :collection
      post :generate_training_assignments, on: :member
      as_routes
    end
    resources :groups do
      as_routes
      collection do get :browse end
      member do get :teaching_plan end
    end
    resources :classrooms do as_routes end
    resources :lecturers do as_routes end
    resources :teaching_places do
      as_routes
      record_select_routes
    end
    resources :charge_cards do as_routes end
    resources :disciplines do
      as_routes
      record_select_routes
    end
    resources :departments, concerns: [:departments] do as_routes end
    resources :semesters do as_routes end
    concerns :training_assignments
    root :to => redirect('/supervisor/lecturers')
  end

##### Администраторский раздел #####

  namespace :admin do
    resources :users do as_routes end
    resources :dept_heads do as_routes end
    resources :editors do as_routes end
    resources :supervisors do as_routes end
    resources :admins do as_routes end
    resources :departments do
      as_routes
      record_select_routes
    end
    resources :faculty_heads do as_routes end
    resources :faculties do
      as_routes
      record_select_routes
    end
    root :to => redirect('/admin/dept_heads')
  end

##### Аутентификация #####

  devise_for :user, :skip => [:sessions]
  devise_scope :user do
    get    'user/login' => 'devise/sessions#new',      :as => :new_user_session
    post   'user/login' => 'devise/sessions#create',    :as => :user_session
    delete 'user/logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  match "/:rolename/login" => redirect("/user/login")

  match '/:controller(/:action(/:id))'

end

app/controllers/department/classrooms_controller.rb
class Department::ClassroomsController < Department::BaseController
  active_scaffold :classroom do |conf|
    conf.actions.exclude :create
    conf.columns = [:building, :name, :title, :department, :department_lock, :capacity, :properties]
    conf.update.columns = [:title, :capacity, :properties]
    conf.columns[:building].clear_link
    conf.columns[:department].clear_link
  end

  def before_update_save(record)
    record[:properties] = params[:record][:properties]
  end

  # Records are filtered according to CanCan abilities.

end 

app/controllers/editor/classrooms/charge_cards_controller.rb
# -*- encoding : utf-8 -*-
class Editor::Classrooms::ChargeCardsController < Editor::BaseController
  def index
    charge_card_search = params[:charge_card].to_s.split
    classroom = Classroom.find(params[:classroom_id])
    if classroom.department_lock and classroom.department
      charge_card = ChargeCard.with_recommended_first_for(classroom.department).where(:semester_id => current_semester.id).each do |c|
        c.set_recommended_dept(classroom.department)
      end
    else
      charge_card = ChargeCard.where(:semester_id => current_semester.id)
    end
    charge_card_search.each do |s|
      charge_card = charge_card.select { |c| c.editor_name_include? s }
    end
    respond_to do |format|
      format.json { render :json => charge_card.to_json(:only => [:id], :methods => [:editor_name_with_recommendation])}
    end
  end
end

app/controllers/editor/classrooms/classrooms_controller.rb
# -*- encoding : utf-8 -*-
class Editor::Classrooms::ClassroomsController < Editor::BaseController

  def index
    flash[:error] = nil
    session[:classroom_editor] = {:classrooms => []} unless session[:classroom_editor]
    except = session[:classroom_editor][:classrooms].any? ? session[:classroom_editor][:classrooms] : "0"
    classroom = params[:classroom].to_s.gsub('%', '\%').gsub('_', '\_') + '%'
    @classrooms = Classroom.where(['classrooms.id NOT IN (?) AND classrooms.name ILIKE ?', except, classroom]).includes(:building)
    respond_to do |format|
      format.html
      format.json { render :json => @classrooms.to_json(:only => [:id, :name], :include => { :building => { :only => :name } } )}
    end
  end

  def show
    @days = Timetable.days
    @times = Timetable.times
    @weeks = Timetable.weeks
    @classroom = Classroom.includes(:pairs).find(params[:id])
    unless @classroom
      flash[:error] = 'Нет аудитории с таким названием'
    else
      @pairs = @classroom.pairs.in_semester(current_semester).order("active_at ASC")
      session[:classroom_editor] = {:classrooms => []} unless session[:classroom_editor]
      session[:classroom_editor][:classrooms] << @classroom.id unless session[:classroom_editor][:classrooms].include? @classroom.id
      respond_to do |format|
        format.js
      end
    end
  end

  def edit

  end

  def update

  end

  def destroy
    if session[:classroom_editor].include? :classrooms
      @id = params[:id].to_i
      session[:classroom_editor][:classrooms].delete(@id)
      respond_to do |format|
        format.js
      end
    end
  end
end

app/controllers/editor/classrooms/classrooms_sheets_controller.rb
# -*- encoding : utf-8 -*-
class Editor::Classrooms::ClassroomsSheetsController < Editor::BaseController
  def index
    @buildings = Building.all
  end
  
  def show
    @weeks = Timetable.weeks
    @days = Timetable.days
    @times = Timetable.times
    @building = Building.find_by_id(params[:id].to_i, :include => [{:classrooms => :pairs}])
    #@classrooms_sheet.classrooms = Classroom.all(:include => :pairs, :conditions => {:building_id => @classrooms_sheet.building.id}).sort_by { |c| c.name.to_i}
  end
end

app/controllers/editor/classrooms/pairs_controller.rb
# -*- encoding : utf-8 -*-
class Editor::Classrooms::PairsController < Editor::BaseController
  layout nil
  layout 'application', :except => :edit

  def create
    flash[:error] = nil
    @pair = Pair.new do |p|
      p.classroom_id = params[:classroom_id]
      p.day_of_the_week = params[:day_of_the_week]
      p.pair_number = params[:pair_number]
      p.week = params[:week]
      p.active_at = current_semester.start
      p.expired_at = current_semester.end
    end
    @container = params[:container]
    unless @pair.valid?
      flash[:error] = @pair.errors[:base].to_a.join('<br />').html_safe
      @pair = nil
    else
      @pair.save
    end

    respond_to do |format|
      format.js
    end
  end

  def edit
    @pair = Pair.find_by_id(params[:id])

    respond_to do |format|
      format.js
    end
  end

  def update
    flash[:error] = nil
    @pair = Pair.find_by_id(params[:id].to_i, :include => [:subgroups])
    @prev_pair = @pair.clone
    @prev_pair.readonly!
    if params[:get_subgroups] && params[:pair]
      @pair.attributes = params[:pair]
      unless @pair.valid?
        flash[:error] = @pair.errors[:base].to_a.join('<br />').html_safe
        @pair.reload
      else
        @pair.save
        @pair.subgroups.destroy_all
        @pair.charge_card.jets.each do |jet|
          subgroup = @pair.subgroups.new(:jet_id => jet.id, :number => 0)
          unless subgroup.valid?
            flash[:error] = subgroup.errors[:base].to_a.join('<br />').html_safe
          else
            subgroup.save
          end
        end
        redirect_to :action => 'edit'
      end
    elsif params[:classroom]
      @pair.classroom_id = params[:classroom].to_i
      @pair.day_of_the_week = params[:day_of_the_week].to_i if params[:day_of_the_week]
      @pair.week = params[:week].to_i if params[:week]
      @pair.pair_number = params[:pair_number].to_i if params[:pair_number]
      unless @pair.valid?
        flash[:error] = @pair.errors[:base].to_a.join('<br />').html_safe
        @pair.reload
      else
        @pair.save
      end

      respond_to do |format|
        format.js
      end
    else
      @pair.attributes = params[:pair]
      unless @pair.valid?
        flash[:error] = @pair.errors[:base].to_a.join('<br />').html_safe
        @pair.reload
        @pair.charge_card_id = nil
        @pair.subgroups.destroy_all
        @pair.save
        redirect_to :action => 'edit'
      else
        @pair.save
        
        respond_to do |format|
          format.js
        end
      end
    end
  end

  def destroy
    flash[:error] = nil
    @id = params[:id].to_i
    pair = Pair.find_by_id(@id)
    @pair = pair.clone
    @pair.readonly!
    pair.destroy

    respond_to do |format|
      format.js
    end
  end
end

app/controllers/supervisor/classrooms_controller.rb
# -*- encoding : utf-8 -*-
class Supervisor::ClassroomsController < Supervisor::BaseController
  active_scaffold do |config|
    config.actions << :delete
    config.columns = [:building, :name, :title, :department, :department_lock, :capacity, :properties]
    config.columns[:building].form_ui = :select
    config.columns[:department].form_ui = :select
    config.columns[:department_lock].form_ui = :checkbox
    config.columns[:building].clear_link
    config.columns[:department].clear_link
  end

  def before_update_save(record)
    record[:properties] = params[:record][:properties]
  end

end

app/controllers/timetable/classrooms_controller.rb
class Timetable::ClassroomsController < Timetable::BaseController

  def index
    @buildings = Building.includes(:classrooms).reorder("buildings.id,(substring(classrooms.name, '^[0-9]+'))::int,substring(classrooms.name, '[^0-9_].*$')")
    @buildings = @buildings.where("classrooms.name ILIKE ? OR classrooms.title ILIKE ? OR buildings.name ILIKE ?", *(["%#{params[:classroom]}%"]*3)) if params[:classroom]
    if params[:day_of_the_week] and params[:week] and params[:pair_number]
      week_filter = params[:week] == '0' ? [0,1,2] : [params[:week], 0]
      unwanted_classroom_ids = Pair.where(week: week_filter, day_of_the_week: params[:day_of_the_week], pair_number: params[:pair_number]).pluck(:classroom_id).uniq.compact
      if unwanted_classroom_ids.any?
        @buildings = @buildings.where("classrooms.id NOT IN (#{unwanted_classroom_ids.join(",")})")
      end
    end
    respond_to do |format|
      format.html do
        if @buildings.count == 1 and @buildings.first.classrooms.count == 1
          redirect_to timetable_classroom_path(@buildings.first.classrooms.first)
        end
      end
      format.json do
        render :json => @buildings.to_json(only: [:id, :name], include: {classrooms: {only: [:id, :title, :name]}})
      end
    end
  end

  def show
    @id = params[:id].to_i
    unless @classroom = Classroom.find_by_id(@id)
      suffix = @terminal ? '?terminal=true' : ''
      redirect_to :controller => 'timetable/classrooms' + suffix
    else
      pairs = @classroom.pairs.includes(:subgroups).in_semester(current_semester).flatten
      @days = Timetable.days
      @times = Timetable.times
      @weeks = Timetable.weeks
      @pairs = Array.new(@days.size).map!{Array.new(@times.size).map!{Array.new(@weeks.size + 1).map!{Array.new}}}
      pairs.each do |pair|
        @pairs[pair.day_of_the_week - 1][pair.pair_number - 1][pair.week] << pair
      end
    end
  end

end

app/helpers/department/classrooms_helper.rb
module Department::ClassroomsHelper

  def properties_column(record, column)
    record.properties_human
  end

end

app/helpers/editor/classrooms/charge_cards_helper.rb
# -*- encoding : utf-8 -*-
module Editor::Classrooms::ChargeCardsHelper
end

app/helpers/editor/classrooms/classrooms_helper.rb
# -*- encoding : utf-8 -*-
module Editor::Classrooms::ClassroomsHelper
end

app/helpers/editor/classrooms/classrooms_sheets_helper.rb
# -*- encoding : utf-8 -*-
module Editor::Classrooms::ClassroomsSheetsHelper
  def buildings_for_select
    Building.all.map { |d| [d.name, d.id]}
  end
end

app/helpers/editor/classrooms/groups_helper.rb
# -*- encoding : utf-8 -*-
module Editor::Classrooms::GroupsHelper
end

app/helpers/editor/groups/pairs_helper.rb
# -*- encoding : utf-8 -*-
module Editor::Groups::PairsHelper
end

app/helpers/pairs_helper.rb
# -*- encoding : utf-8 -*-
module PairsHelper
end

app/helpers/supervisor/classrooms_helper.rb
# -*- encoding : utf-8 -*-
module Supervisor::ClassroomsHelper

  def properties_column(record, column)
    record.properties_human
  end

end

app/helpers/timetable/classrooms_helper.rb
module Timetable::ClassroomsHelper
end

app/views/editor/classrooms/pairs/_pair.html.haml
- short_lesson_type = truncate("#{pair.lesson_type}", :length => 6, :omission => '.')
.pair{:id => "#{pair.id}"}
  .management_panel
    - if pair.warnings.any?
      - warning_string = pair.warnings.map{|w| t(w, :scope => 'activerecord.warnings.pair')}.join(", ")
      .warning_sign{:title => warning_string} ⚠
    .edit{:pair_id => "#{pair.id}"}
      = image_tag('edit_16.png')
    .destroy{:pair_id => "#{pair.id}"}
      = image_tag('delete_16.png')
  .pair_content
    %abbr{:title => "#{pair.discipline}"}
      = "#{pair.short_discipline}"
    %br
    %abbr{:title => "#{pair.lesson_type}"}
      = "#{short_lesson_type}"
    %br
    - if pair.lecturer && pair.lecturer_id
      %abbr{:title => "#{pair.lecturer_full}"}
        = link_to "#{pair.lecturer}", timetable_lecturer_path(pair.lecturer_id), :target => '_blank'
    - if pair.assistant && pair.assistant_id
      , 
      %abbr{:title => "#{pair.assistant_full}"}
        = link_to "#{pair.assistant}", timetable_lecturer_path(pair.assistant_id), :target => '_blank'
    %br
    - if pair.groups
      - pair.groups.each_with_index do |group, i|
        = ", " unless i == 0
        = link_to "#{group.name}", timetable_group_path(group.id), :target => '_blank'
    %br
    = "#{pair.active_at} — #{pair.expired_at}"

app/views/editor/classrooms/pairs/_pair_edit.html.haml
.update_form{:id => "pair_edit_#{@pair.id.to_s}"}
  = form_for([:editor, :classrooms, @pair], :remote => true) do |f|
    %p{:id => "week_block"}
      %br
      = f.radio_button :week, 0
      = 'Обе недели'
      %br
      = f.radio_button :week, 1
      = 'Первая неделя'
      %br
      = f.radio_button :week, 2
      = 'Вторая неделя'
    %p{:id => "charge_card_block"}
      = 'Карта нагрузки'
      %br
      %input{:class => "charge_card", :id => "charge_card_name", :size => 20, :value => "#{@pair.charge_card.editor_name if @pair.charge_card}"}
      = f.hidden_field :charge_card_id
    .subgroups
      = f.fields_for :subgroups, @pair.subgroups do |s|
        = render 'subgroup', :s => s
    .warnings
      - @pair.warnings.each do |warning|
        %p= t(warning, :scope => 'activerecord.warnings.pair')
    %p#dates_block_show
      %a{:href => ""} Начало и окончание занятий?
    %p{:id => "dates_block"}
      %span{:id => "active_at_label"} Начало занятий
      %br
      = f.text_field :active_at, {:value => @pair.active_at.strftime('%d.%m.%Y'),:size => 10}
      %br
      %span{:id => "expired_at_label"} Окончание занятий
      %br
      = f.text_field :expired_at, {:value => @pair.expired_at.strftime('%d.%m.%Y'), :size => 10}
    %p
      = f.submit 'Сохранить'

app/views/editor/classrooms/pairs/_subgroup.html.haml
.subgroup
  = 'Группа ' + s.object.jet.group.name
  %br
  - options = [['Без подгрупп', 0], ['Первая подгруппа', 1], ['Вторая подгруппа', 2]]
  - options += Array.new(3) { |index| ["Подгруппа № %d" % (index+3), index+3] }
  = s.select :number, options_for_select(options, s.object.number)

app/views/editor/classrooms/pairs/create.js.erb
jQuery(document).ready(function($){
  <% if @pair %>
    $('#<%= escape_javascript @container %>').prepend('<%= escape_javascript render :partial => @pair %>');
    $('#<%= @pair.id %>').draggable();
    $.get('/editor/classrooms/pairs/' + '<%= @pair.id %>' + '/edit');
  <% elsif flash[:error] %>
    $('.workspace').prepend('<div id="error"></div>');
    $('#error').append('<%= escape_javascript flash[:error] %>');
    $('#error').dialog({
      draggable: false,
      modal: true
    });
  <% end %>
});

app/views/editor/classrooms/pairs/destroy.js.erb
jQuery(document).ready(function($){
    $('#<%= @id %>').fadeOut('fast', function() {
        $('#<%= @id %>').remove();
    });
    <% if @pair.week == 0 %>    
      $('#td_grid<%= @pair.classroom_id %>_week0_day<%= @pair.day_of_the_week %>_time<%= @pair.pair_number %>').replaceWith('<%= escape_javascript render :partial => "/editor/classrooms/classrooms/container", :locals => {:pair => @pair, :colspan => 1} %>');
    <% end %>
});

app/views/editor/classrooms/pairs/edit.js.erb
jQuery(document).ready(function($){

    $.ajaxSetup({
    "error":function() {   
        $('.workspace').prepend('<div id="error"></div>');
        $('#error').append('<p>Произошла ошибка при выполнении запроса</p>');
        $('#error').dialog({
            draggable: false,
            modal: true
        });
    }});

    $('#pair_edit_<%= @pair.id %>').remove();
    $('body').prepend('<%= escape_javascript render :partial => 'pair_edit' %>');
    var dlg = $('#pair_edit_<%= @pair.id %>').dialog({
        beforeClose: function(event, ui) {
            $('#pair_edit_<%= @pair.id %>').remove();
        },
        closeText: 'Закрыть',
        draggable: false,
        modal: true,
        position: 'top',
        title: 'Редактировать пару'
    });
    
    <% if flash[:error] %>
      $('.workspace').prepend('<div id="error"></div>');
      $('#error').append('<%= escape_javascript flash[:error] %>');
      $('#error').dialog({
        draggable: false,
        modal: true
      });
    <% end %>

    $('.edit_pair').submit(function() {
        dlg.dialog("close");
    });
    
    $('.charge_card').autocomplete({
        disabled: false,
        minLength: 2,
        source: function(request, response) {
            $.getJSON('/editor/classrooms/charge_cards.json', {
              charge_card: request.term,
              classroom_id: <%= @pair.classroom.id %>,
            },
            function(data) {
                var charge_cards = new Array(0);
                $.each(data, function(index, i) {
                    charge_cards.push({ label: i.charge_card.editor_name_with_recommendation, value: i.charge_card.id });
                });
                response(charge_cards);
            });
        },
        select: function(event, ui) {
            $('#pair_charge_card_id').val(ui.item.value);
            $('#charge_card_name').val(ui.item.label);
            $.post($('#edit_pair_<%= @pair.id %>').attr('action'),
                $('#edit_pair_<%= @pair.id %>').serialize() + '&get_subgroups=true',
                null, "script");
            return false;
        }
    });
    
    $('.charge_card').focus(function() {
        $('.charge_card').val('');
    });
    
    $('#dates_block_show a').click( function () {
        $('#dates_block').slideToggle('slow');
        return false;
    });

    var months = [
        'Январь',
        'Февраль',
        'Март',
        'Апрель',
        'Май',
        'Июнь',
        'Июль',
        'Август',
        'Сентябрь',
        'Октябрь',
        'Ноябрь',
        'Декабрь'];
    $('#pair_active_at').datepicker({
        firstDay: 1,
        dateFormat: 'dd.mm.yy',
        monthNames: months,
        showOn: 'button',
        buttonImage: '/images/calendar.gif',
        buttonImageOnly: true
    });
    $('#pair_expired_at').datepicker({
        firstDay: 1,
        dateFormat: 'dd.mm.yy',
        monthNames: months,
        showOn: 'button',
        buttonImage: '/images/calendar.gif',
        buttonImageOnly: true
    });
    
    var grid_context = $('.pair#<%= @pair.id %>').parent().parent();
    var current = $('.receiver', grid_context).not('.hidden_receiver');
    var index = current.prevAll('.receiver').length;
    var indexparam = $('<input id="pair_index" name="index" type="hidden" value="'+index+'">');
    $('#pair_edit_<%= @pair.id %> > form').append(indexparam);
    
});

app/views/editor/classrooms/pairs/update.js.erb
<%
  prev_container = "_grid#{@prev_pair.classroom_id}_week#{@prev_pair.week}_day#{@prev_pair.day_of_the_week}_time#{@prev_pair.pair_number}"
  container = "_grid#{@pair.classroom_id}_week#{@pair.week}_day#{@pair.day_of_the_week}_time#{@pair.pair_number}"
%>
jQuery(document).ready(function($){
    <% if flash[:error] %>
      $('.workspace').prepend('<div id="error"></div>');
      $('#error').append('<%= escape_javascript flash[:error] %>');
      $('#error').dialog({
        draggable: false,
        modal: true
      });
    <% end %>
    $("#pair_edit_<%= @pair.id %> .warnings").empty();
    <% @pair.warnings.each do |warning| %>
      $("#pair_edit_<%= @pair.id %> .warnings").append("<p><%= escape_javascript t(warning, :scope => 'activerecord.warnings.pair') %></p>");
    <% end %>
    $('#<%= @pair.id %>').remove();
    if ($('#td<%= escape_javascript container %>').length == 0) {
      $('#td_grid<%= @pair.classroom_id %>_week1_day<%= @pair.day_of_the_week %>_time<%= @pair.pair_number %>').replaceWith('<%= escape_javascript render :partial => "/editor/classrooms/classrooms/container", :locals => {:pair => @pair, :colspan => 2} %>');
      $('#td_grid<%= @pair.classroom_id %>_week2_day<%= @pair.day_of_the_week %>_time<%= @pair.pair_number %>').remove();
    }
    <% if @prev_pair.week == 0 && (@prev_pair.classroom_id != @pair.classroom_id || @prev_pair.week != @pair.week || @prev_pair.day_of_the_week != @pair.day_of_the_week || @prev_pair.pair_number != @pair.pair_number) %>
      $('#td<%= escape_javascript prev_container %>').replaceWith('<%= escape_javascript render :partial => "/editor/classrooms/classrooms/container", :locals => {:pair => @prev_pair, :colspan => 1, :index => params[:index]} %>');
    <% end %>
    <% if flash[:error] %>
    $(".receiver", $('#td<%= escape_javascript container %>')).filter(":not(.hidden_receiver)").append('<%= escape_javascript render :partial => @pair %>');
    <% else %>
    $('#container<%= escape_javascript container %><%= "_index#{params[:index]}" %>').append('<%= escape_javascript render :partial => @pair %>');
    <% end %>
    $('#<%= @pair.id %>').draggable();
    $('.receiver').droppable({
        accept: '.pair',
        over: function(){ $(this).addClass('hovered_receiver');},
        out: function(){ $(this).removeClass('hovered_receiver');},
        drop: function(event, ui){
            $.post('/editor/classrooms/pairs/' + ui.draggable.attr('id'), {
                _method: 'put',
                classroom: $(this).attr('grid_id'),
                week: $(this).attr('week_number'),
                day_of_the_week: $(this).attr('day_of_the_week'),
                pair_number: $(this).attr('pair_number'),
                container: $(this).attr('id'),
                index: $('.receiver', $(this).parent()).not('.hidden_receiver').prevAll('.receiver').length
            }, null, "script");
            $(this).removeClass('hovered_receiver');
        }
    });
});