config/routes.rb
# -*- encoding : utf-8 -*-
Taurus::Application.routes.draw do

##### Общие части #####

  concern :departments do
    get :charge_cards_form, on: :member
  end

  concern :teaching_places do
    get :training_assignments, on: :member
  end

  concern :training_assignments do
    resources :training_assignments do
      as_routes
      get :report, on: :collection
      get :join_selected, on: :collection
      get :split_by_disciplines, on: :member
      get :split_by_groups, on: :member
      get :new_charge_cards, on: :collection
      post :create_charge_cards, on: :collection
    end
  end

  concern :speciality_teaching_plans do
    get :teaching_plan_import, on: :collection
    post :teaching_plan_import, on: :collection
    get :teaching_plan, on: :member
  end

##### Отображение расписания #####

  root :to => redirect('/timetable/groups')

  namespace :timetable do
    resources :groups do
      get :qrcode, on: :member
    end
    resources :lecturers
    resources :classrooms
    root :to => redirect('/timetable/groups')
  end

##### Общее #####

post 'semesters/change' => 'application#change_current_semester'
resources :semesters, :only => [:index]
match 'help(/:page(.:format))', :controller => 'help', :action => 'show', :page => /(\w*\/?\w*)*/, :defaults => { :page => 'index' }, :as => :help

##### Редакторский раздел #####

  namespace :editor do
    root :to => redirect('/editor/groups')

    # Редактор по аудиториям
    namespace :classrooms do
      resources :classrooms
      resources :pairs
      resources :charge_cards
      resources :classrooms_sheets
      root :to => 'classrooms#index'
    end

    # Редактор по группам
    namespace :groups do
      resources :groups
      resources :pairs
      resources :classrooms
      resources :charge_cards
      root :to => 'groups#index'
    end

    # Справочные материалы
    namespace :reference do
      resources :groups
      resource :groups_list do
        resources :groups
      end
      resources :departments do as_routes end
      resources :disciplines do as_routes end
      resources :teaching_places do as_routes end
      resources :charge_cards do as_routes end
      get 'teaching_plans' => 'teaching_plans#index'
      get 'teaching_plans/:group_id' => 'teaching_plans#show'
      root :to => redirect('/editor/reference/classroom_sheets')
    end
  end

##### Раздел заведующего кафедрой #####

  get  'dept_head(/*parts)' => 'department/base#change_current_department'
  get  'department' => 'department/base#change_current_department'
  post 'department/change' => 'department/base#change_current_department'
  namespace :department, :path => '/department/:department_id', :department_id => /\d+/ do
    resources :teaching_places do
      as_routes
      record_select_routes
      get :training_assignments, on: :member
    end
    resources :disciplines do
      as_routes
      record_select_routes
    end
    resources :groups do
      as_routes
      collection do get :browse end
      member do
        post :select
        get  :teaching_plan
      end
    end
    resources :lecturers do
      as_routes
      record_select_routes
    end
    resources :charge_cards do
      as_routes
    end
    resources :specialities, concerns: [:speciality_teaching_plans] do
      as_routes
      member do
        get :add_charge_cards
        post :create_charge_cards
      end
    end
    resources :classrooms do as_routes end
    resource :charge_card_form, only: [:show, :edit, :save]
    concerns :training_assignments
    root :to => redirect {|env, req| "/department/#{req.params[:department_id]}/teaching_places" }
  end

##### Раздел деканата #####

  get  'faculty' => 'faculty/base#change_current_faculty'
  post 'faculty/change' => 'faculty/base#change_current_faculty'

  namespace :faculty, :path => '/faculty/:faculty_id', :faculty_id => /\d+/ do
    resources :specialities do
      as_routes
      concerns :speciality_teaching_plans
      member do
        post :generate_training_assignments
      end
      collection do
        post :generate_training_assignments
      end
    end
    resources :lecturers do as_routes end
    resources :groups do
      as_routes
      record_select_routes
    end
    resources :teaching_places do
      as_routes
      record_select_routes
    end
    resources :disciplines do
      as_routes
      record_select_routes
    end
    resources :departments, concerns: [:departments] do as_routes end
    concerns :training_assignments
    root :to => redirect('/supervisor/lecturers')
  end

##### Раздел супервайзера #####

  namespace :supervisor do
    resources :faculties do as_routes end
    resources :specialities, concerns: [:speciality_teaching_plans] do
      post :generate_training_assignments, on: :collection
      post :generate_training_assignments, on: :member
      as_routes
    end
    resources :groups do
      as_routes
      collection do get :browse end
      member do get :teaching_plan end
    end
    resources :classrooms do as_routes end
    resources :lecturers do as_routes end
    resources :teaching_places do
      as_routes
      record_select_routes
    end
    resources :charge_cards do as_routes end
    resources :disciplines do
      as_routes
      record_select_routes
    end
    resources :departments, concerns: [:departments] do as_routes end
    resources :semesters do as_routes end
    concerns :training_assignments
    root :to => redirect('/supervisor/lecturers')
  end

##### Администраторский раздел #####

  namespace :admin do
    resources :users do as_routes end
    resources :dept_heads do as_routes end
    resources :editors do as_routes end
    resources :supervisors do as_routes end
    resources :admins do as_routes end
    resources :departments do
      as_routes
      record_select_routes
    end
    resources :faculty_heads do as_routes end
    resources :faculties do
      as_routes
      record_select_routes
    end
    root :to => redirect('/admin/dept_heads')
  end

##### Аутентификация #####

  devise_for :user, :skip => [:sessions]
  devise_scope :user do
    get    'user/login' => 'devise/sessions#new',      :as => :new_user_session
    post   'user/login' => 'devise/sessions#create',    :as => :user_session
    delete 'user/logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  match "/:rolename/login" => redirect("/user/login")

  match '/:controller(/:action(/:id))'

end

app/controllers/department/groups_controller.rb
# -*- encoding : utf-8 -*-
class Department::GroupsController < Department::BaseController
  before_filter :customize_active_scaffold
  record_select :search_on => :name, :order_by => :name
  active_scaffold do |config|
    config.actions << :delete
    config.columns = [:name, :forming_year, :course, :population]
    config.create.columns.exclude :course
    config.update.columns.exclude :course
    config.action_links.add :teaching_plan, :label => "Учебный план", :type => :member, :page => true
  end

  def teaching_plan
    @group = Group.find(params[:id])
    @charge_cards = @group.charge_cards.where(:semester_id => current_semester.id)
    @lesson_types = LessonType.all(:order => :id)
    @teaching_plans = TeachingPlan.find_all_by_speciality_id_and_course_and_semester(
      @group.speciality_id, @group.course, current_semester.number
    )
    discipline_ids = (@charge_cards.map{|cc| cc.discipline_id} + @teaching_plans.map{|tp| tp.discipline_id}).uniq
    @disciplines = Discipline.find(discipline_ids, :order => :name)
    render "application/groups/teaching_plans/show"
  end

protected

  def customize_active_scaffold
    actions = [:create, :update, :delete]
    config  = active_scaffold_config
    if nested? and nested_parent_record.department_id != current_department.id
      actions.each do |action|
        config.actions.exclude action
      end
    else
      actions.each do |action|
        config.actions << action
      end
    end
  end

end

app/controllers/editor/groups/groups_controller.rb
# -*- encoding : utf-8 -*-
class Editor::Groups::GroupsController < Editor::BaseController

  def index
    flash[:error] = nil
    session[:group_editor] = {:groups => []} unless session[:group_editor]
    @group = Group.find(params[:group_id]) if params[:group_id]
    except = session[:group_editor][:groups].any? ? session[:group_editor][:groups] : "0"
    classroom = params[:group].to_s.gsub('%', '\%').gsub('_', '\_') + '%'
    @groups = Group.all(:conditions => ['id NOT IN (?) AND name LIKE ?', except, classroom], :order => "name")
    respond_to do |format|
      format.html
      format.json { render :json => @groups.to_json(:only => [:name], :methods => [:descriptive_name]) }
    end
  end

  def show
    @days = Timetable.days
    @times = Timetable.times
    @weeks = Timetable.weeks
    @group = Group.for_groups_editor.from_param(params[:id])
    unless @group
      flash[:error] = 'Нет группы с таким названием'
    else
      session[:group_editor] = {:groups => []} unless session[:group_editor]
      session[:group_editor][:groups] << @group.id unless session[:group_editor][:groups].include? @group.id
      @groups = session[:group_editor][:groups]
      respond_to do |format|
        format.js
      end
    end
  end

  def edit

  end

  def update

  end

  def destroy
    if session[:group_editor].include? :groups
      @id = params[:id].to_i
      session[:group_editor][:groups].delete(@id)
      @groups = session[:group_editor][:groups]

      respond_to do |format|
        format.js
      end
    end
  end
  
end

app/controllers/editor/groups/pairs_controller.rb
# -*- encoding : utf-8 -*-
class Editor::Groups::PairsController < ApplicationController
  before_filter :preload_data, :except => [:destroy]

  def new
  end

  def create
    keys = %w(week day_of_the_week pair_number).map {|k| k.to_sym }
    pair_params = Hash[keys.map {|i| [i, (params[i] || nil)] }]
    pair_params[:classroom_id] = nil
    @pair = Pair.includes(Pair::RELATIONS_TO_INCLUDE).where(pair_params).first_or_initialize
    @pair.active_at = current_semester.start
    @pair.expired_at = current_semester.end
    unless @pair.save
      conflict_params = [params[:day_of_the_week], params[:pair_number], nil]
      pairs = Pair.find_all_by_day_of_the_week_and_pair_number_and_classroom_id(*conflict_params)
      charge_card_ids = @group.charge_cards.map{ |c| c.id }
      pairs.find_all { |p| charge_card_ids.include? p.charge_card_id or p.charge_card_id.nil? }.each { |p| p.destroy }
      unless @pair.save
        flash[:error] = @pair.errors[:base].to_a.join('<br />').html_safe
      end
    end
    respond_to do |format|
      format.js { render :edit }
    end
  end

  def edit
    @pair = Pair.includes(Pair::RELATIONS_TO_INCLUDE).find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def update
    flash[:error] = nil
    logger.debug 'Loading pair...'
    @pair = Pair.includes(Pair::RELATIONS_TO_INCLUDE).find(params[:id])
    @prev_pair = @pair.dup
    @prev_pair.readonly!
    if params[:get_subgroups] && params[:pair]
      @pair.transaction do
        logger.debug 'Saving pair. Charge card or classroom is changed...'
        @pair.attributes = params[:pair]
        if @pair.charge_card_id_changed? and @pair.charge_card
          logger.debug 'Saving pair. Updating subgroups...'
          @pair.subgroups.destroy_all
          @pair.charge_card.jets.each do |jet|
            subgroup = @pair.subgroups.new(:jet_id => jet.id, :number => 0)
            subgroup.number = params[:subgroup] if jet.group_id == @group.id and params[:subgroup]
            unless subgroup.save
              flash[:error] = subgroup.errors[:base].to_a.join('<br />').html_safe
            end
          end
        end
        # If there is preferred classrooms for charge card, try to set it up.
        if @pair.charge_card_id_changed? and @pair.charge_card and @pair.classroom_id.nil?
          logger.debug 'Saving pair. Try to set up classroom...'
          @pair.charge_card.preferred_classrooms.each do |classroom|
            @pair.classroom = classroom
            break if @pair.valid?
          end
          @pair.classroom_id = nil if @pair.invalid?
        end
        logger.debug 'Saving pair. Validate and save...'
        success = @pair.save
        respond_to do |format|
          @pair.reload
          @pairs = @group.pairs_with_subgroups
          format.js do
            logger.debug 'Start rendering template...'
            flash[:error] = @pair.errors[:base].to_a.join('<br />').html_safe unless success
            render :edit
            raise ActiveRecord::Rollback unless success
          end
        end
      end
    elsif params.include? :pair_number and params.include? :day_of_the_week
      # If it's a pair movement into another day/pair number
      # First, remember old subgroup and week_number
      logger.debug 'Moving pair...'
      subgroup = @pair.subgroups.select{|s| s.jet.group_id==@group.id}.first
      old_week = @pair.week
      old_sub = subgroup.number
      # Second, move the pair into target cell (account target subgroup and week number)
      @pair.day_of_the_week = params[:day_of_the_week].to_i if params[:day_of_the_week]
      @pair.pair_number = params[:pair_number].to_i if params[:pair_number]
      @pair.week = params[:week] ? params[:week].to_i : 0
      subgroup.number = params[:subgroup] ? params[:subgroup].to_i : 0
      # So, try to save it
      unless @pair.valid? and subgroup.valid?
        flash[:error] = @pair.errors[:base].to_a.join('<br />').html_safe
        @pair.reload
        subgroup.reload
      else
        subgroup.save
        @pair.save
      end
      respond_to do |format|
        @pairs = @group.pairs_with_subgroups
        format.js
      end
    else
      # Simple edit
      logger.debug 'Saving pair and closing editor...'
      @pair.attributes = params[:pair]
      unless @pair.save
        flash[:error] = @pair.errors[:base].to_a.join('<br />').html_safe
        @pair.reload
        respond_to do |format|
          format.js { render :edit }
        end
      else
        @pairs = @group.pairs_with_subgroups
        respond_to do |format|
          format.js
        end
      end
    end
  end

  def destroy
    flash[:error] = nil
    @id = params[:id].to_i
    pair = Pair.find(@id)
    @pair = pair.clone
    @pair.readonly!
    pair.destroy

    respond_to do |format|
      format.js
    end
  end

  protected

  def preload_data
    @group = Group.for_groups_editor.find(params[:group_id])
    @charge_cards = ChargeCard.joins(:jets).includes(:jets).where(
        :jets => {:group_id => @group.id}, :semester_id => current_semester.id
    ).select("charge_cards.id, charge_cards.editor_name").order(:editor_name)
    @classrooms = Classroom.all_with_recommended_first_for(@group.department)
  end

end

app/controllers/editor/reference/groups_controller.rb
# -*- encoding : utf-8 -*-
class Editor::Reference::GroupsController < Editor::BaseController
  before_filter :find_group
  def index
    except = session[:groups_lists][:groups].any? ? session[:groups_lists][:groups] : 0
    group = params[:group].to_s.gsub('%', '\%').gsub('_', '\_') + '%'
    @groups = Group.all(:conditions => ['id NOT IN (?) AND name LIKE ?', except, group])

    respond_to do |format|
      format.json { render :json => @groups.to_json(:only => [:id], :methods => [:descriptive_name]) }
    end
  end

  def create
    unless @group
      flash[:error] = "Группа не найдена"
    else
      session[:groups_lists][:groups].push(params[:id].to_i).uniq!
    end

    respond_to do |format|
      format.js
    end
  end

  def destroy
    unless @group
      flash[:error] = "Группа не найдена"
    else
      session[:groups_lists][:groups].delete(params[:id].to_i)
    end

    respond_to do |format|
      format.js
    end
  end

  private

  def find_group
    session[:groups_lists] = {:groups => []} unless session[:groups_lists]
    @group = Group.find_by_id(params[:id])
  end
end

app/controllers/faculty/groups_controller.rb
# -*- encoding : utf-8 -*-
class Faculty::GroupsController < Faculty::BaseController
  record_select :search_on => :name, :order_by => :name
  active_scaffold do |config|
    config.actions << :delete
    config.columns = [:name, :forming_year, :course, :speciality, :population]
    config.create.columns.exclude :course
    config.update.columns.exclude :course
    config.columns[:speciality].form_ui = :select
    config.action_links.add :teaching_plan, :label => "Учебный план", :type => :member, :page => true
  end

  def teaching_plan
    @group = Group.find(params[:id])
    @charge_cards = @group.charge_cards.where(:semester_id => current_semester.id)
    @lesson_types = LessonType.all(:order => :id)
    @teaching_plans = TeachingPlan.find_all_by_speciality_id_and_course_and_semester(
      @group.speciality_id, @group.course, current_semester.number
    )
    discipline_ids = (@charge_cards.map{|cc| cc.discipline_id} + @teaching_plans.map{|tp| tp.discipline_id}).uniq
    @disciplines = Discipline.find(discipline_ids, :order => :name)
    render "application/groups/teaching_plans/show"
  end

end

app/helpers/department/groups_helper.rb
# -*- encoding : utf-8 -*-
module Department::GroupsHelper
end

app/helpers/editor/classrooms/groups_helper.rb
# -*- encoding : utf-8 -*-
module Editor::Classrooms::GroupsHelper
end

app/helpers/editor/groups/groups_helper.rb
# -*- encoding : utf-8 -*-
module Editor::Groups::GroupsHelper
end

app/helpers/editor/groups/pairs_helper.rb
# -*- encoding : utf-8 -*-
module Editor::Groups::PairsHelper
end

app/helpers/timetable/groups_helper.rb
# -*- encoding : utf-8 -*-
module Timetable::GroupsHelper
end

app/views/editor/groups/groups/_grid.html.haml
.group_editor{:id => "group_editor_#{group.id}", :group_id => group.id}
  %table
    %caption
      .closebutton{:class => "group_editor_close", :group_id => "#{group.id}"}
      #{group.name}
      %p.population Учащихся: #{group.population or "(не указано)"} чел.
    %thead
      %tr
        %th.subgroup 1 подгруппа
        %th.subgroup 2 подгруппа
    - @days.each_with_index do |day, day_counter|
      %tbody
        = render :partial => 'row', :collection => @times, :as => :time, :locals => {:group => group, :day_counter => day_counter}

app/views/editor/groups/groups/_legend.html.haml
.group_editor.legend
  %table.legend
    %caption &nbsp;
    %col.weekday
    %col.pairtime
    %col.weeknum
    %thead
      %tr
        %th{:colspan => 3} &nbsp;
    - Timetable.days.each_with_index do |day, day_counter|
      %tbody
        - Timetable.times.each_with_index do |time, time_counter|
          %tr
            - if time_counter.zero?
              %th.weekday{:rowspan => Timetable.times.count*2}
                %div #{day}
            %th{:rowspan => 2}
              = raw(time.gsub(" - ", "<br/>—<br/>"))
            %th.weeknum
              1 неделя
          %tr
            %th.weeknum
              2 неделя

app/views/editor/groups/groups/_pair.html.haml
- short_lesson_type = truncate("#{pair.lesson_type}", :length => 6, :omission => '.')
- pair_class = "pair_#{group.id}" + (pair.classroom.nil? ? " pair_wrong" : "")
.pair{:id => "#{pair.id}", :class => pair_class }
  .management_panel
    - if pair.warnings.any?
      - warning_string = pair.warnings.map{|w| t(w, :scope => 'activerecord.warnings.pair')}.join(", ")
      .warning_sign{:title => warning_string} ⚠
    .edit{:pair_id => "#{pair.id}"}
      = image_tag('edit_16.png')
    .destroy{:pair_id => "#{pair.id}"}
      = image_tag('delete_16.png')
  .pair_content
    .pair_discipline
      %abbr{:title => "#{pair.discipline}"}
        #{pair.short_discipline}
      %abbr{:title => "#{pair.lesson_type}"}
        (#{short_lesson_type})
    .pair_classroom
      = pair.classroom.try(:full_name)
    .pair_lecturer
      - if pair.lecturer && pair.lecturer_id
        %abbr{:title => "#{pair.lecturer_full}"}
          = link_to "#{pair.lecturer}", timetable_lecturer_path(pair.lecturer_id), :target => '_blank'
      - if pair.assistant && pair.assistant_id
        , 
        %abbr{:title => "#{pair.assistant_full}"}
          = link_to "#{pair.assistant}", timetable_lecturer_path(pair.assistant_id), :target => '_blank'
    - if s and s > 2
      = "#{s}-я подгруппа"       
    .pair_dates
      = "#{pair.active_at} — #{pair.expired_at}"

app/views/editor/groups/groups/_recv_mgmt_panel.html.haml
.grid_mgmt_panel
  %img.receiver_add{:src => image_path("plus.png"), :alt => "+"}
  %img.receiver_prev{:src => image_path("control-180.png"), :alt => "<"}
  %img.receiver_next{:src => image_path("control.png"), :alt => ">"}
  .receiver_count 1/#{rcv_count}

app/views/editor/groups/groups/_row.html.haml
%tr
  %td.timeslot{:colspan => 2, :id => "group_editor_grid#{group.id}_day#{day_counter+1}_pair#{time_counter+1}", :grid_id => "#{group.id}", :day_of_the_week => "#{day_counter+1}", :pair_number => "#{time_counter+1}", :week => 0}
    - @pair_groups = pairs_split_by_time(group.pairs_with_subgroups_for_timeslot(day_counter+1, time_counter+1, current_semester))
    - if @pair_groups.any?
      = render :partial => '/editor/groups/groups/timeslot', :collection => @pair_groups, :as => :pair_group, :locals => {:group => group, :day => day_counter+1, :pair => time_counter+1}
    = render :partial => '/editor/groups/groups/recv_mgmt_panel', :locals => {:rcv_count => @pair_groups.count || 1}

app/views/editor/groups/groups/_subgroups.html.haml
- subgroups = []
- to_display = []
- pairs.sort_by { |p| p[0].expired_at }.each do |b|
  - if !subgroups.include?(b[1])
    - subgroups << b[1]
    - subgroups << 0 # Если есть пара с подгруппами, то пара без подгрупп уже не влезет 
    - to_display << b

- if to_display.size > 0
  -# Если без подгрупп или есть только одна пара 3-ей или ещё какой подгруппы
  - if subgroups.max == 0 or (subgroups.max > 2 and to_display.size == 1)
    - if cellsintop.empty?
      - cellsintop << 1
    %td{:colspan => 2, :rowspan => (singlerow ? 2 : 1)}
      - pair = to_display.first[0]
      = render '/editor/groups/groups/pair', :pair => pair, :s => to_display.first[1], :group => group
  - else
    - if cellsintop.empty?
      - cellsintop << 2
    -# Если есть пара третьей или большей подгруппы и есть место куда её воткнуть
    - to_display.find_all{ |elem| elem[1] > 2 }.each do |elem|
      - if subgroups.max > 2 and to_display.size == 2 and to_display.size - skipcell.size > 0
        - elem[2] = elem[1] # elem[1] - подгруппа-позиция, elem[2] - реальная подгруппа пары
        - elem[1] = to_display.find_all{ |elem| elem[1] == 1 }.size > 1 ? 2 : 1
    - 1.upto(2) do |sub|
      - if skipcell.include?(sub)
        - skipcell - [sub]
        - next
      - sp = to_display.find_all{ |elem| elem[1] == sub }
      - if sp.size > 0
        - pair = sp.first[0]
        - a = {:rowspan=> singlerow ? 2 : pair.week.zero?? 2 : 1}
        - if pair.week == 0 and !singlerow
          - skipcell << sub
        %td{a}
          = render '/editor/groups/groups/pair', :pair => pair, :s => sp.first[2], :group => group
      - else
        %td.empty{:rowspan=> singlerow ? 2 : 1}
          .receiver{ :class => "receiver_#{group.id}", :id => "#{id}_week#{week}_sub#{sub}", :grid_id => "#{group.id}", :day_of_the_week => "#{day}", :pair_number => "#{pair_number}", :index => index, :week => week, :sub => sub}
- else
  - a = (cellsintop.include?(2) ? {:colspan=>2} : {})
  %td.empty{a}
    .receiver{ :class => "receiver_#{group.id}", :id => "#{id}_week#{week}", :grid_id => "#{group.id}", :day_of_the_week => "#{day}", :pair_number => "#{pair_number}", :index => index, :week => week}

app/views/editor/groups/groups/_timeslot.html.haml
- first_week_pairs = pair_group.find_all {|p| p[0].week == 1 }
- second_week_pairs = pair_group.find_all {|p| p[0].week == 2 }
- both_week_pairs = pair_group.find_all {|p| p[0].week == 0 }
- id = "group_editor_grid#{group.id}_day#{day}_pair#{pair}_index#{pair_group_counter}"
- ts_class = "hidden" unless pair_group_counter.zero?
- if both_week_pairs.empty? and first_week_pairs.empty? and second_week_pairs.empty?
  .receiver{ :class => "receiver_#{group.id} #{ts_class}", :id => "#{id}_week0", :grid_id => "#{group.id}", :day_of_the_week => "#{day}", :pair_number => "#{pair}", :index => pair_group_counter, :week => 0 }
- else
  %table.timeslot{:id => id, :class => ts_class}
    %tbody
      - if both_week_pairs.any? and first_week_pairs.empty? and second_week_pairs.empty?
        %tr
          = render '/editor/groups/groups/subgroups', :group => group, :pairs => both_week_pairs, :skipcell => [], :singlerow => true, :cellsintop => [], :week => 0, :day => day, :pair_number => pair, :index => pair_group_counter, :id => id
        %tr
      - else
        - skipcell = []
        - cellsintop = []
        %tr
          - if first_week_pairs.any? or both_week_pairs.any?
            = render '/editor/groups/groups/subgroups', :group => group, :pairs => first_week_pairs+both_week_pairs, :skipcell => skipcell, :singlerow => false, :cellsintop => cellsintop, :week => 1, :day => day, :pair_number => pair, :index => pair_group_counter, :id => id
          - else
            %td{:colspan => 2}
              .receiver{ :class => "receiver_#{group.id}", :id => "#{id}_week1", :grid_id => "#{group.id}", :day_of_the_week => "#{day}", :pair_number => "#{pair}", :index => pair_group_counter, :week => 1}
        %tr
          - if second_week_pairs.any?
            = render '/editor/groups/groups/subgroups', :group => group, :pairs => second_week_pairs, :skipcell => skipcell, :singlerow => false, :cellsintop => cellsintop, :week => 2, :day => day, :pair_number => pair, :index => pair_group_counter, :id => id
          - else
            - sub = (skipcell.include?(1) ? 2 : 1)
            %td{:colspan => skipcell.empty?? 2 : 1}
              .receiver{ :class => "receiver_#{group.id}", :id => "#{id}_week2_sub#{sub}", :grid_id => "#{group.id}", :day_of_the_week => "#{day}", :pair_number => "#{pair}", :index => pair_group_counter, :week => 2, :sub => sub}

app/views/editor/groups/groups/destroy.js.erb
<% grid_id = escape_javascript "group_editor_#{@id}" %>
jQuery(document).ready(function($){
    $('#<%= grid_id %>').fadeOut('fast', function() {
        $('#<%= grid_id %>').remove();
        $('#group_name').focus();
        return false;
    });
});

app/views/editor/groups/groups/index.html.haml
- title "Редактор расписания по группам"

.info
  %p<
    <strong>Внимание!</strong> Вы составляете расписание на #{current_semester}.

#group_form
  %p
    Группа:
    %input{:id => "group_name", :size => 10}

#group_workspace
  = render :partial => 'legend'
  - # If groups are specified, show their grids immediately!
  - if @group
    = javascript_tag("jQuery.get('"+url_for([:editor, :groups, @group])+"');")
  - elsif session[:group_editor].include? :groups and session[:group_editor][:groups].any?
    - session[:group_editor][:groups].each do |group_id|
      - group = Group.find(group_id, :select => 'id, name')
      .group_editor{:id => "group_editor_#{group.id}"}
      = javascript_tag("jQuery.get('"+editor_groups_group_path(group)+"');")

app/views/editor/groups/groups/show.js.erb
jQuery(document).ready(function($){
    var editor = '<%= escape_javascript render :partial => "grid", :locals => {:group => @group} %>';
    var editor_id = '#group_editor_<%= @group.id %>';
    if ($(editor_id).length)
      $(editor_id).replaceWith(editor);
    else
      $('#group_workspace').append(editor);
    <%= render :partial => "/editor/groups/pairs/drag_and_drop", :locals => {:group => @group} %>
    $('#group_name').val('');
});