config/routes.rb
# -*- encoding : utf-8 -*-
Taurus::Application.routes.draw do

##### Общие части #####

  concern :departments do
    get :charge_cards_form, on: :member
  end

  concern :teaching_places do
    get :training_assignments, on: :member
  end

  concern :training_assignments do
    resources :training_assignments do
      as_routes
      get :report, on: :collection
      get :join_selected, on: :collection
      get :split_by_disciplines, on: :member
      get :split_by_groups, on: :member
      get :new_charge_cards, on: :collection
      post :create_charge_cards, on: :collection
    end
  end

  concern :speciality_teaching_plans do
    get :teaching_plan_import, on: :collection
    post :teaching_plan_import, on: :collection
    get :teaching_plan, on: :member
  end

##### Отображение расписания #####

  root :to => redirect('/timetable/groups')

  namespace :timetable do
    resources :groups do
      get :qrcode, on: :member
    end
    resources :lecturers
    resources :classrooms
    root :to => redirect('/timetable/groups')
  end

##### Общее #####

post 'semesters/change' => 'application#change_current_semester'
resources :semesters, :only => [:index]
match 'help(/:page(.:format))', :controller => 'help', :action => 'show', :page => /(\w*\/?\w*)*/, :defaults => { :page => 'index' }, :as => :help

##### Редакторский раздел #####

  namespace :editor do
    root :to => redirect('/editor/groups')

    # Редактор по аудиториям
    namespace :classrooms do
      resources :classrooms
      resources :pairs
      resources :charge_cards
      resources :classrooms_sheets
      root :to => 'classrooms#index'
    end

    # Редактор по группам
    namespace :groups do
      resources :groups
      resources :pairs
      resources :classrooms
      resources :charge_cards
      root :to => 'groups#index'
    end

    # Справочные материалы
    namespace :reference do
      resources :groups
      resource :groups_list do
        resources :groups
      end
      resources :departments do as_routes end
      resources :disciplines do as_routes end
      resources :teaching_places do as_routes end
      resources :charge_cards do as_routes end
      get 'teaching_plans' => 'teaching_plans#index'
      get 'teaching_plans/:group_id' => 'teaching_plans#show'
      root :to => redirect('/editor/reference/classroom_sheets')
    end
  end

##### Раздел заведующего кафедрой #####

  get  'dept_head(/*parts)' => 'department/base#change_current_department'
  get  'department' => 'department/base#change_current_department'
  post 'department/change' => 'department/base#change_current_department'
  namespace :department, :path => '/department/:department_id', :department_id => /\d+/ do
    resources :teaching_places do
      as_routes
      record_select_routes
      get :training_assignments, on: :member
    end
    resources :disciplines do
      as_routes
      record_select_routes
    end
    resources :groups do
      as_routes
      collection do get :browse end
      member do
        post :select
        get  :teaching_plan
      end
    end
    resources :lecturers do
      as_routes
      record_select_routes
    end
    resources :charge_cards do
      as_routes
    end
    resources :specialities, concerns: [:speciality_teaching_plans] do
      as_routes
      member do
        get :add_charge_cards
        post :create_charge_cards
      end
    end
    resources :classrooms do as_routes end
    resource :charge_card_form, only: [:show, :edit, :save]
    concerns :training_assignments
    root :to => redirect {|env, req| "/department/#{req.params[:department_id]}/teaching_places" }
  end

##### Раздел деканата #####

  get  'faculty' => 'faculty/base#change_current_faculty'
  post 'faculty/change' => 'faculty/base#change_current_faculty'

  namespace :faculty, :path => '/faculty/:faculty_id', :faculty_id => /\d+/ do
    resources :specialities do
      as_routes
      concerns :speciality_teaching_plans
      member do
        post :generate_training_assignments
      end
      collection do
        post :generate_training_assignments
      end
    end
    resources :lecturers do as_routes end
    resources :groups do
      as_routes
      record_select_routes
    end
    resources :teaching_places do
      as_routes
      record_select_routes
    end
    resources :disciplines do
      as_routes
      record_select_routes
    end
    resources :departments, concerns: [:departments] do as_routes end
    concerns :training_assignments
    root :to => redirect('/supervisor/lecturers')
  end

##### Раздел супервайзера #####

  namespace :supervisor do
    resources :faculties do as_routes end
    resources :specialities, concerns: [:speciality_teaching_plans] do
      post :generate_training_assignments, on: :collection
      post :generate_training_assignments, on: :member
      as_routes
    end
    resources :groups do
      as_routes
      collection do get :browse end
      member do get :teaching_plan end
    end
    resources :classrooms do as_routes end
    resources :lecturers do as_routes end
    resources :teaching_places do
      as_routes
      record_select_routes
    end
    resources :charge_cards do as_routes end
    resources :disciplines do
      as_routes
      record_select_routes
    end
    resources :departments, concerns: [:departments] do as_routes end
    resources :semesters do as_routes end
    concerns :training_assignments
    root :to => redirect('/supervisor/lecturers')
  end

##### Администраторский раздел #####

  namespace :admin do
    resources :users do as_routes end
    resources :dept_heads do as_routes end
    resources :editors do as_routes end
    resources :supervisors do as_routes end
    resources :admins do as_routes end
    resources :departments do
      as_routes
      record_select_routes
    end
    resources :faculty_heads do as_routes end
    resources :faculties do
      as_routes
      record_select_routes
    end
    root :to => redirect('/admin/dept_heads')
  end

##### Аутентификация #####

  devise_for :user, :skip => [:sessions]
  devise_scope :user do
    get    'user/login' => 'devise/sessions#new',      :as => :new_user_session
    post   'user/login' => 'devise/sessions#create',    :as => :user_session
    delete 'user/logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  match "/:rolename/login" => redirect("/user/login")

  match '/:controller(/:action(/:id))'

end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  protect_from_forgery # See ActionController::RequestForgeryProtection for details
  clear_helpers
  before_filter :set_current_semester
  before_filter :log_additional_data

  rescue_from CanCan::AccessDenied do |exception|
    raise exception if Rails.env.development?
    render file: "#{Rails.root}/public/403", formats: [:html], status: 403, layout: false
  end

  helper_method :current_semester
  def current_semester
    @current_semester
  end

  def change_current_semester
    set_current_semester
    redirect_to (request.referer.blank?? timetable_groups_path : request.referer)
  end

  helper_method :current_department
  def current_department
    @current_department ||= (params[:department_id].present? and Department.find(params[:department_id]))
    @current_department ||= Department.accessible_by(current_ability, :update).where(id: session[:current_department_id]).first
    @current_department ||= Department.accessible_by(current_ability, :update).first
    session[:current_department_id] = @current_department.id
    return @current_department
  end

  helper_method :current_faculty
  def current_faculty
    @current_faculty ||= (params[:faculty_id].present? and Faculty.find(params[:faculty_id]))
    @current_faculty ||= Faculty.accessible_by(current_ability, :update).where(id: session[:current_faculty_id]).first
    @current_faculty ||= Faculty.accessible_by(current_ability, :update).first
    session[:current_faculty_id] = @current_faculty.id
    return @current_faculty
  end

protected

  def after_sign_in_path_for(resource)
    return admin_dept_heads_path if current_user.admin?
    return supervisor_lecturers_path if current_user.supervisor?
    return editor_groups_root_path if current_user.editor?
    return faculty_training_assignments_path(current_user.faculty_ids.first) if current_user.faculty_ids.any?
    return department_teaching_places_path(current_user.department_ids.first) if current_user.department_ids.any?
    return request.referrer
  end

  def set_current_semester
    unless params[:semester_id]
      unless session[:current_semester_id]
        year = Date.today.year - (Date.today.month < 8 ? 1 : 0)
        number = Date.today.month < 8 ? 2 : 1
        @current_semester = Semester.published.where(:year => year, :number => number, :full_time => true).first
        @current_semester = Semester.published.first unless @current_semester
        @current_semester = Semester.first unless @current_semester
      else
        @current_semester = Semester.find(session[:current_semester_id])
      end
    else
      @current_semester = Semester.find(params[:semester_id])
    end
    @current_semester = Semester.first unless @current_semester
    Group.current_semester = @current_semester
    session[:current_semester_id] = @current_semester.id
  end

  helper_method :current_ability
  def current_ability
    @current_ability ||= Ability.new(current_user, params)
  end

  def log_additional_data
    request.env['exception_notifier.exception_data'] = {
      current_user: (current_user if user_signed_in?),
      current_semester: current_semester,
      current_faculty: (current_faculty if session[:current_faculty_id].present?),
      current_department: (current_department if session[:current_department_id].present?),
    }
  end

end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
# Methods added to this helper will be available to all templates in the application.
module ApplicationHelper

  def title(title_text)
    content_for(:title) { title_text }
  end

  def week_number (date=Date.today)
    semester_start_year = date.month < 9 ? date.year-1 : date.year
    semester_start = Date.strptime("#{semester_start_year}-09-01")
    startweek_no = semester_start.cwday.in?([6,7]) ? semester_start.cweek+1 : semester_start.cweek
    current_week = date.cweek + (date.year > semester_start_year ? 52 : 0)
    return 1 + ((current_week - startweek_no) % 2)
  end

  def pairs_split_by_time(pairs)
    return [[]] if pairs.nil? or pairs.empty?
    # Step 1. Find dates — groups separators
    activation_dates = pairs.map{|p| p[0].active_at}.uniq.sort
    separators = [activation_dates.min]
    until activation_dates.empty?
      sep = pairs.select{|p| p[0].active_at == activation_dates.min}.max_by{|p| p[0].expired_at}[0].expired_at
      separators << sep
      activation_dates = activation_dates.find_all { |d| d > sep }
    end
    # Step 2. Assign pairs to their groups
    groups = []
    separators.each do |date|
      group = pairs.find_all {|p| p[0].expired_at <= date}
      pairs = pairs - group
      group += pairs.find_all {|p| p[0].active_at < date}
      groups << group if group.any?
    end
    return groups
  end

  def markdown(text)
    MarkdownHandler.parser.render(text).html_safe
  end

  def departments_change_grouped_options_for_select(accessible_departments=Department.all)
    departments_grouped_options_for_select(accessible_departments, current_department.id, nil)
  end

  def departments_grouped_options_for_select(departments=Department.all, current=nil, prompt=nil)
    faculties = Faculty.joins(:departments).reorder('departments.gosinsp_code').includes(:departments)
    groups = faculties.map do |f|
      depts = f.departments & departments
      if depts.any?
        [f.name, depts.map{|d| [d.name, d.id] }]
      else
        nil
      end
    end.compact
    grouped_options_for_select(groups, current, prompt)
  end

  def faculties_change_options_for_select(accessible_faculties=Faculty.all)
    options_for_select(accessible_faculties.map{|f| [f.name, f.id] }, current_faculty.id)
  end

end

app/views/application/menu/_admin.html.haml
%li #{ link_to 'Администраторы системы', admin_admins_path, class: (:current if params[:controller] == "admin/admins") }
%li #{ link_to 'Супервайзеры', admin_supervisors_path, class: (:current if params[:controller] == "admin/supervisors") }
%li #{ link_to 'Диспетчеры', admin_editors_path, class: (:current if params[:controller] == "admin/editors") }
%li #{ link_to 'Заведующие кафедр', admin_dept_heads_path, class: (:current if params[:controller] == "admin/dept_heads") }
%li #{ link_to 'Зам. деканов по УР', admin_faculty_heads_path, class: (:current if params[:controller] == "admin/faculty_heads") }
%li #{ link_to 'Все пользователи', admin_users_path, class: (:current if params[:controller] == "admin/users") }

app/views/application/menu/_department.html.haml
= render 'change_department'
%li #{ link_to 'Преподаватели кафедры', department_teaching_places_path(current_department.id), class: (:current if params[:controller] == "department/teaching_places") }
%li #{ link_to 'Дисциплины', department_disciplines_path(current_department.id), class: (:current if params[:controller] == "department/disciplines") }
%li #{ link_to 'Специальности', department_specialities_path(current_department.id), class: (:current if params[:controller] == "department/specialities") }
%li #{ link_to 'Аудитории', department_classrooms_path(current_department.id), class: (:current if params[:controller] == "department/classrooms") }
%li #{ link_to 'Учебные поручения', report_department_training_assignments_path(current_department.id), class: (:current if params[:controller] == "department/training_assignments") }
%li #{ link_to 'Карточка нагрузки', department_charge_card_form_path(current_department.id), class: (:current if params[:controller] == "department/charge_card_forms") }

app/views/application/menu/_editor.html.haml
%li #{ link_to 'Редактор по аудиториям', editor_classrooms_root_path, class: (:current if params[:controller] == "editor/classrooms/classrooms") }
%li #{ link_to 'Редактор по группам', editor_groups_root_path, class: (:current if params[:controller] == "editor/groups/groups") }
%li #{ link_to 'Занятость аудиторий', editor_classrooms_classrooms_sheets_path, class: (:current if params[:controller] == "editor/classrooms/classrooms_sheets") }
%li #{ link_to 'Листы расписания', new_editor_reference_groups_list_path, class: (:current if params[:controller] == "editor/reference/groups_list") }
%li.submenu
  #{ link_to 'Карты нагрузки', editor_reference_departments_path, class: (:current if %w(departments teaching_plans).any? {|cnt| params[:controller] == "editor/reference/#{cnt}" }) }
  %menu.submenu
    %li #{ link_to 'Карты по преподавателям и дисциплинам', editor_reference_departments_path, class: (:current if params[:controller] == "editor/reference/departments") }
    %li #{ link_to "Учебные планы по группам", url_for(:controller => "reference/teaching_plans", :action => "index"), class: (:current if params[:controller] == "editor/reference/teaching_plans") }

app/views/application/menu/_faculty.html.haml
= render 'change_faculty'
%li #{ link_to 'Кафедры', faculty_departments_path(current_faculty.id), class: (:current if params[:controller] == "faculty/faculties") }
%li #{ link_to 'Специальности', faculty_specialities_path(current_faculty.id), class: (:current if params[:controller] == "faculty/specialities") }
%li #{ link_to 'Учебные поручения', faculty_training_assignments_path(current_faculty.id), class: (:current if params[:controller] == "faculty/training_assignments") }

app/views/application/menu/_main.html.haml
- if user_signed_in?
  %nav
    %menu.main_menu
      - if current_user.supervisor? or current_user.admin?
        = render 'application/menu/supervisor'
        %li.submenu
          #{link_to "Редактор расписания", editor_groups_root_path, class: (:current if params[:controller].starts_with?('editor'))}
          %menu.editor_menu
            = render 'application/menu/editor'
        %li.submenu
          #{link_to "Деканат", department_teaching_places_path(current_department.id), class: (:current if params[:controller].starts_with?('faculty'))}
          %menu.faculty_menu
            = render 'application/menu/faculty'
        %li.submenu
          #{link_to "Зав. кафедрой", department_teaching_places_path(current_department.id), class: (:current if params[:controller].starts_with?('department'))}
          %menu.department_menu
            = render 'application/menu/department'
        - if current_user.admin?
          %li.submenu
            #{link_to "Пользователи", admin_dept_heads_path, class: (:current if params[:controller].starts_with?('admin'))}
            %menu.admin_menu
              = render 'application/menu/admin'
      - elsif current_user.editor?
        = render 'application/menu/editor'
      - elsif current_user.faculties.any?
        = render 'application/menu/faculty'
        %li.submenu
          #{link_to "Зав. кафедрой", department_teaching_places_path(current_department.id), class: (:current if params[:controller].starts_with?('department'))}
          %menu.department_menu
            = render 'application/menu/department'
      - else
        = render 'application/menu/department'
      %li #{ link_to 'Выход', destroy_user_session_path, :class => "red", :method => :delete }
      %li.semester= render 'change_semester'

app/views/application/menu/_supervisor.html.haml
%li #{ link_to 'Факультеты', supervisor_faculties_path, class: (:current if params[:controller] == "supervisor/faculties") }
%li #{ link_to 'Специальности', supervisor_specialities_path, class: (:current if params[:controller] == "supervisor/specialities") }
%li #{ link_to 'Группы', supervisor_groups_path, class: (:current if params[:controller] == "supervisor/groups") }
%li #{ link_to 'Преподаватели', supervisor_lecturers_path, class: (:current if params[:controller] == "supervisor/lecturers") }
%li #{ link_to 'Аудитории', supervisor_classrooms_path, class: (:current if params[:controller] == "supervisor/classrooms") }
%li #{ link_to 'Семестры', supervisor_semesters_path, class: (:current if params[:controller] == "supervisor/semesters") }
%li #{ link_to 'Учебные поручения', supervisor_training_assignments_path, class: (:current if params[:controller] == "supervisor/training_assignments") }